# vim: ft=yaml

---
minimum_pre_commit_version: 1.15.2
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: trailing-whitespace   # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending     # Replaces or checks mixed line ending.
        args: [--fix=lf]
      - id: end-of-file-fixer     # Makes sure files end in a newline and only a newline.
      - id: check-merge-conflict  # Check for files that contain merge conflict strings.
      - id: check-ast             # Simply check whether files parse as valid python.

  # ----- Local Hooks ----------------------------------------------------------------------------------------------->
  - repo: local
    hooks:
      - id: sort-pylint-spelling-words
        name: Sort PyLint Spelling Words File
        entry: python .pre-commit-hooks/sort-pylint-spelling-words.py
        language: system
        files: ^\.pylint-spelling-words$

      - id: check-changelog-entries
        name: Check Changelog Entries
        entry: python .pre-commit-hooks/check-changelog-entries.py
        language: system
  # <---- Local Hooks ------------------------------------------------------------------------------------------------

  # ----- Formatting ------------------------------------------------------------------------------------------------>
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        alias: reorder-python-imports-3.5
        name: Reorder imports on required Py3.5 compat files
        args: [
          --py3-plus,
          --application-directories=.:src:examples/echo-extension/src
        ]
        files: (?x)^(
            noxfile
            |
            setup
            |
            docs/.*
            |
            examples/.*
            |
            tests/.*
            |
            .pre-commit-hooks/.*
            |
            src/saltfactories/(
              __init__
              |
              __main__
              |
              exceptions
            )
          )\.py$
        exclude: (?x)^(
            src/saltfactories/(
              version
              |
              downgraded/.*
            )
          )\.py$

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        alias: reorder-python-imports-3.5-plus
        name: Reorder imports on Py3.7+ files
        args: [
          --py3-plus,
          --add-import=from __future__ import annotations,
          --application-directories=.:src:examples/echo-extension/src
        ]
        exclude: (?x)^(
            noxfile
            |
            setup
            |
            docs/.*
            |
            examples/.*
            |
            tests/.*
            |
            .pre-commit-hooks/.*
            |
            src/saltfactories/(
              __init__
              |
              __main__
              |
              version
              |
              exceptions
              |
              downgraded/.*
            )
          )\.py$

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        name: Rewrite Code to be Py3.5+
        args:
          - --py37-plus
          - --keep-runtime-typing
        exclude: (?x)^(
            noxfile
            |
            setup
            |
            docs/.*
            |
            examples/.*
            |
            tests/.*
            |
            .pre-commit-hooks/.*
            |
            src/saltfactories/(
              __init__
              |
              __main__
              |
              version
              |
              exceptions
              |
              downgraded/.*
            )
          )\.py$

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [-l 100]
        exclude: ^(src/saltfactories/(version|downgraded/.*)\.py)$

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        args: [--skip-errors]
        files: ^(.*\.rst|docs/.*\.rst|src/saltfactories/.*\.py)$
        exclude: ^(src/saltfactories/downgraded/.*\.py)$
        additional_dependencies:
          - black==22.3.0
  # <---- Formatting -------------------------------------------------------------------------------------------------

  # ----- Remove Typing - Py3.5 Support  ---------------------------------------------------------------------------->
  - repo: https://github.com/s0undt3ch/downgrade-source
    rev: v3.0.0
    hooks:
      - id: downgrade-source
        name: Downgrade source code into a separate package to support Py<3.7
        files: ^src/.*\.py$
        exclude: ^(src/saltfactories/((__init__|version|downgraded/.*)\.py))$
        args:
          - --target-version=3.5
          - --pkg-path=src/saltfactories
          - --skip-checker=nostarimports
          - --skip-checker=nooverriddenbuiltins
          - --per-file-skip-checker=src/saltfactories/utils/__init__.py:nounusableimports
  # <---- Remove Typing - Py3.5 Support  -----------------------------------------------------------------------------

  # ----- Security -------------------------------------------------------------------------------------------------->
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-salt
        name: Run bandit against Salt
        args: [--silent, -lll, --skip, B701]
        exclude: >
            (?x)^(
                tests/.*
            )$
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.4"
    hooks:
      - id: bandit
        alias: bandit-tests
        name: Run bandit against the test suite
        args: [--silent, -lll, --skip, B701]
        files: ^tests/.*
  # <---- Security ---------------------------------------------------------------------------------------------------

  # ----- Code Analysis --------------------------------------------------------------------------------------------->
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
      - id: flake8
        exclude: ^((src/saltfactories/(version|downgraded/.*)|\.pre-commit-hooks/.*)\.py)$
        additional_dependencies:
        - flake8-mypy-fork
        - flake8-docstrings
        - flake8-typing-imports
        - pydocstyle>=6.1.1

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        name: Run mypy against source
        files: ^((src|tests)/.*\.py)$
        exclude: ^(src/saltfactories/downgraded/.*\.py)$
        args: [--strict]
        additional_dependencies:
          - pytest
          - types-attrs
          - types-requests
          - types-setuptools
          - pytest-tempdir>=2019.9.16
          - pytest-helpers-namespace>=2021.4.29
          - pytest-skip-markers>=1.1.3
          - pytest-system-statistics>=1.0.2
          - pytest-shell-utilities>=1.5.0
  # <---- Code Analysis ----------------------------------------------------------------------------------------------
